// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TcgTournamentManager.Infrastructure.Data;

#nullable disable

namespace TcgTournamentManager.Infrastructure.Migrations
{
    [DbContext(typeof(TournamentDbContext))]
    [Migration("20260624130753_AddTournamentFormatAndElimination")]
    partial class AddTournamentFormatAndElimination
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TcgTournamentManager.Core.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PerformedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SyncOperation")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<DateTime>("SyncVersion")
                        .HasColumnType("datetime2");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("AUDIT_LOG", (string)null);
                });

            modelBuilder.Entity("TcgTournamentManager.Core.Entities.ByeHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("int");

                    b.Property<string>("SyncOperation")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<DateTime>("SyncVersion")
                        .HasColumnType("datetime2");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.Property<int>("TournamentPlayerId")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TournamentPlayerId");

                    b.HasIndex("TournamentId", "TournamentPlayerId", "RoundNumber")
                        .IsUnique();

                    b.ToTable("BYE_HISTORY", (string)null);
                });

            modelBuilder.Entity("TcgTournamentManager.Core.Entities.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsBye")
                        .HasColumnType("bit");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("bit");

                    b.Property<int?>("PlayerAId")
                        .HasColumnType("int");

                    b.Property<int?>("PlayerBId")
                        .HasColumnType("int");

                    b.Property<int>("RoundId")
                        .HasColumnType("int");

                    b.Property<string>("SyncOperation")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<DateTime>("SyncVersion")
                        .HasColumnType("datetime2");

                    b.Property<int>("TableNumber")
                        .HasColumnType("int");

                    b.Property<int?>("TopCutBracketId")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.Property<int?>("WinnerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerAId");

                    b.HasIndex("PlayerBId");

                    b.HasIndex("TopCutBracketId")
                        .IsUnique()
                        .HasFilter("[TopCutBracketId] IS NOT NULL");

                    b.HasIndex("WinnerId");

                    b.HasIndex("RoundId", "TableNumber")
                        .IsUnique();

                    b.ToTable("MST_MATCH", (string)null);
                });

            modelBuilder.Entity("TcgTournamentManager.Core.Entities.MatchResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerAGameWins")
                        .HasColumnType("int");

                    b.Property<int>("PlayerAMatchPoints")
                        .HasColumnType("int");

                    b.Property<int>("PlayerBGameWins")
                        .HasColumnType("int");

                    b.Property<int>("PlayerBMatchPoints")
                        .HasColumnType("int");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ResultType")
                        .HasColumnType("int");

                    b.Property<string>("SyncOperation")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<DateTime>("SyncVersion")
                        .HasColumnType("datetime2");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MatchId")
                        .IsUnique();

                    b.ToTable("MATCH_RESULT", (string)null);
                });

            modelBuilder.Entity("TcgTournamentManager.Core.Entities.OrganizerUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SyncOperation")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<DateTime>("SyncVersion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("MST_ORGANIZER_USER", (string)null);
                });

            modelBuilder.Entity("TcgTournamentManager.Core.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalPlayerId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SyncOperation")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<DateTime>("SyncVersion")
                        .HasColumnType("datetime2");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExternalPlayerId")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("MST_PLAYER", (string)null);
                });

            modelBuilder.Entity("TcgTournamentManager.Core.Entities.Round", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("bit");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("int");

                    b.Property<int>("RoundType")
                        .HasColumnType("int");

                    b.Property<string>("SyncOperation")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<DateTime>("SyncVersion")
                        .HasColumnType("datetime2");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId", "RoundNumber", "RoundType")
                        .IsUnique();

                    b.ToTable("MST_ROUND", (string)null);
                });

            modelBuilder.Entity("TcgTournamentManager.Core.Entities.Standing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("GWPercent")
                        .HasPrecision(8, 4)
                        .HasColumnType("decimal(8,4)");

                    b.Property<int>("GameLosses")
                        .HasColumnType("int");

                    b.Property<int>("GameWins")
                        .HasColumnType("int");

                    b.Property<int>("MatchPoints")
                        .HasColumnType("int");

                    b.Property<int>("MatchesDrawn")
                        .HasColumnType("int");

                    b.Property<int>("MatchesLost")
                        .HasColumnType("int");

                    b.Property<int>("MatchesPlayed")
                        .HasColumnType("int");

                    b.Property<int>("MatchesWon")
                        .HasColumnType("int");

                    b.Property<decimal>("OGWPercent")
                        .HasPrecision(8, 4)
                        .HasColumnType("decimal(8,4)");

                    b.Property<decimal>("OMWPercent")
                        .HasPrecision(8, 4)
                        .HasColumnType("decimal(8,4)");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<string>("SyncOperation")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<DateTime>("SyncVersion")
                        .HasColumnType("datetime2");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.Property<int>("TournamentPlayerId")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TournamentPlayerId");

                    b.HasIndex("TournamentId", "Rank");

                    b.HasIndex("TournamentId", "TournamentPlayerId")
                        .IsUnique();

                    b.ToTable("TOURNAMENT_STANDING", (string)null);
                });

            modelBuilder.Entity("TcgTournamentManager.Core.Entities.TopCutBracket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("bit");

                    b.Property<int>("MatchPosition")
                        .HasColumnType("int");

                    b.Property<int?>("NextBracketId")
                        .HasColumnType("int");

                    b.Property<int?>("PlayerAId")
                        .HasColumnType("int");

                    b.Property<int?>("PlayerBId")
                        .HasColumnType("int");

                    b.Property<int>("Round")
                        .HasColumnType("int");

                    b.Property<string>("SyncOperation")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<DateTime>("SyncVersion")
                        .HasColumnType("datetime2");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.Property<int?>("WinnerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NextBracketId");

                    b.HasIndex("PlayerAId");

                    b.HasIndex("PlayerBId");

                    b.HasIndex("WinnerId");

                    b.HasIndex("TournamentId", "Round", "MatchPosition")
                        .IsUnique();

                    b.ToTable("TOP_CUT_BRACKET", (string)null);
                });

            modelBuilder.Entity("TcgTournamentManager.Core.Entities.Tournament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentRound")
                        .HasColumnType("int");

                    b.Property<int?>("EliminationLossCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FirstRoundPairingMode")
                        .HasColumnType("int");

                    b.Property<string>("GameTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("HasElimination")
                        .HasColumnType("bit");

                    b.Property<int>("MatchFormat")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Organizer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("SyncOperation")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<DateTime>("SyncVersion")
                        .HasColumnType("datetime2");

                    b.Property<int>("TopCutSize")
                        .HasColumnType("int");

                    b.Property<int>("TotalSwissRounds")
                        .HasColumnType("int");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventDate");

                    b.HasIndex("Status");

                    b.ToTable("MST_TOURNAMENT", (string)null);
                });

            modelBuilder.Entity("TcgTournamentManager.Core.Entities.TournamentPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeckName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsDropped")
                        .HasColumnType("bit");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SyncOperation")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<DateTime>("SyncVersion")
                        .HasColumnType("datetime2");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TournamentId", "PlayerId")
                        .IsUnique()
                        .HasFilter("[SyncOperation] <> 'D'");

                    b.HasIndex("TournamentId", "PlayerNumber")
                        .IsUnique()
                        .HasFilter("[SyncOperation] <> 'D'");

                    b.ToTable("TOURNAMENT_PLAYER", (string)null);
                });

            modelBuilder.Entity("TcgTournamentManager.Core.Entities.ByeHistory", b =>
                {
                    b.HasOne("TcgTournamentManager.Core.Entities.Tournament", "Tournament")
                        .WithMany()
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TcgTournamentManager.Core.Entities.TournamentPlayer", "TournamentPlayer")
                        .WithMany("ByeHistories")
                        .HasForeignKey("TournamentPlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tournament");

                    b.Navigation("TournamentPlayer");
                });

            modelBuilder.Entity("TcgTournamentManager.Core.Entities.Match", b =>
                {
                    b.HasOne("TcgTournamentManager.Core.Entities.TournamentPlayer", "PlayerA")
                        .WithMany()
                        .HasForeignKey("PlayerAId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TcgTournamentManager.Core.Entities.TournamentPlayer", "PlayerB")
                        .WithMany()
                        .HasForeignKey("PlayerBId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TcgTournamentManager.Core.Entities.Round", "Round")
                        .WithMany("Matches")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TcgTournamentManager.Core.Entities.TopCutBracket", "TopCutBracket")
                        .WithOne("Match")
                        .HasForeignKey("TcgTournamentManager.Core.Entities.Match", "TopCutBracketId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("TcgTournamentManager.Core.Entities.TournamentPlayer", "Winner")
                        .WithMany()
                        .HasForeignKey("WinnerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PlayerA");

                    b.Navigation("PlayerB");

                    b.Navigation("Round");

                    b.Navigation("TopCutBracket");

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("TcgTournamentManager.Core.Entities.MatchResult", b =>
                {
                    b.HasOne("TcgTournamentManager.Core.Entities.Match", "Match")
                        .WithOne("Result")
                        .HasForeignKey("TcgTournamentManager.Core.Entities.MatchResult", "MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("TcgTournamentManager.Core.Entities.Round", b =>
                {
                    b.HasOne("TcgTournamentManager.Core.Entities.Tournament", "Tournament")
                        .WithMany("Rounds")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("TcgTournamentManager.Core.Entities.Standing", b =>
                {
                    b.HasOne("TcgTournamentManager.Core.Entities.Tournament", "Tournament")
                        .WithMany("Standings")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TcgTournamentManager.Core.Entities.TournamentPlayer", "TournamentPlayer")
                        .WithMany()
                        .HasForeignKey("TournamentPlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tournament");

                    b.Navigation("TournamentPlayer");
                });

            modelBuilder.Entity("TcgTournamentManager.Core.Entities.TopCutBracket", b =>
                {
                    b.HasOne("TcgTournamentManager.Core.Entities.TopCutBracket", "NextBracket")
                        .WithMany()
                        .HasForeignKey("NextBracketId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TcgTournamentManager.Core.Entities.TournamentPlayer", "PlayerA")
                        .WithMany()
                        .HasForeignKey("PlayerAId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TcgTournamentManager.Core.Entities.TournamentPlayer", "PlayerB")
                        .WithMany()
                        .HasForeignKey("PlayerBId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TcgTournamentManager.Core.Entities.Tournament", "Tournament")
                        .WithMany("TopCutBrackets")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TcgTournamentManager.Core.Entities.TournamentPlayer", "Winner")
                        .WithMany()
                        .HasForeignKey("WinnerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("NextBracket");

                    b.Navigation("PlayerA");

                    b.Navigation("PlayerB");

                    b.Navigation("Tournament");

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("TcgTournamentManager.Core.Entities.TournamentPlayer", b =>
                {
                    b.HasOne("TcgTournamentManager.Core.Entities.Player", "Player")
                        .WithMany("TournamentPlayers")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TcgTournamentManager.Core.Entities.Tournament", "Tournament")
                        .WithMany("TournamentPlayers")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("TcgTournamentManager.Core.Entities.Match", b =>
                {
                    b.Navigation("Result");
                });

            modelBuilder.Entity("TcgTournamentManager.Core.Entities.Player", b =>
                {
                    b.Navigation("TournamentPlayers");
                });

            modelBuilder.Entity("TcgTournamentManager.Core.Entities.Round", b =>
                {
                    b.Navigation("Matches");
                });

            modelBuilder.Entity("TcgTournamentManager.Core.Entities.TopCutBracket", b =>
                {
                    b.Navigation("Match");
                });

            modelBuilder.Entity("TcgTournamentManager.Core.Entities.Tournament", b =>
                {
                    b.Navigation("Rounds");

                    b.Navigation("Standings");

                    b.Navigation("TopCutBrackets");

                    b.Navigation("TournamentPlayers");
                });

            modelBuilder.Entity("TcgTournamentManager.Core.Entities.TournamentPlayer", b =>
                {
                    b.Navigation("ByeHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
